import 'package:flutter/material.dart';

/// Severity level of a security alert.
enum AlertSeverity { critical, high, medium, low, info }

/// Source module that generated the alert.
enum AlertSource { observer, shield, deceptor, phantomSnare, vault }

/// Represents a security alert generated by any module.
class SecurityAlert {
  final String id;
  final String title;
  final String description;
  final AlertSeverity severity;
  final AlertSource source;
  final DateTime timestamp;
  final Map<String, dynamic> metadata;
  bool isAcknowledged;

  SecurityAlert({
    required this.id,
    required this.title,
    required this.description,
    required this.severity,
    required this.source,
    required this.timestamp,
    this.metadata = const {},
    this.isAcknowledged = false,
  });

  Color get severityColor {
    switch (severity) {
      case AlertSeverity.critical:
        return const Color(0xFFFF3D57);
      case AlertSeverity.high:
        return const Color(0xFFFF6B35);
      case AlertSeverity.medium:
        return const Color(0xFFFFBF00);
      case AlertSeverity.low:
        return const Color(0xFF58A6FF);
      case AlertSeverity.info:
        return const Color(0xFF00E5FF);
    }
  }

  String get severityLabel {
    switch (severity) {
      case AlertSeverity.critical:
        return 'CRITICAL';
      case AlertSeverity.high:
        return 'HIGH';
      case AlertSeverity.medium:
        return 'MEDIUM';
      case AlertSeverity.low:
        return 'LOW';
      case AlertSeverity.info:
        return 'INFO';
    }
  }

  String get sourceLabel {
    switch (source) {
      case AlertSource.observer:
        return 'Observer';
      case AlertSource.shield:
        return 'Shield';
      case AlertSource.deceptor:
        return 'Deceptor';
      case AlertSource.phantomSnare:
        return 'Phantom Snare';
      case AlertSource.vault:
        return 'Vault';
    }
  }

  IconData get sourceIcon {
    switch (source) {
      case AlertSource.observer:
        return Icons.radar;
      case AlertSource.shield:
        return Icons.shield;
      case AlertSource.deceptor:
        return Icons.psychology;
      case AlertSource.phantomSnare:
        return Icons.gps_off;
      case AlertSource.vault:
        return Icons.dashboard;
    }
  }
}
