/// Represents a GPS/RF spoofing event generated by the Phantom Snare.
class SpoofingEvent {
  final String id;
  final double realLatitude;
  final double realLongitude;
  final double phantomLatitude;
  final double phantomLongitude;
  final String triggerSource;
  final SpoofingType type;
  final DateTime timestamp;
  final bool isActive;

  const SpoofingEvent({
    required this.id,
    required this.realLatitude,
    required this.realLongitude,
    required this.phantomLatitude,
    required this.phantomLongitude,
    required this.triggerSource,
    required this.type,
    required this.timestamp,
    this.isActive = true,
  });

  /// Distance in km between real and phantom coordinates (approximate).
  double get deceptionDistanceKm {
    final latDiff = (realLatitude - phantomLatitude).abs();
    final lonDiff = (realLongitude - phantomLongitude).abs();
    // Rough Euclidean approximation in degrees → km (1° ≈ 111 km)
    return (latDiff * latDiff + lonDiff * lonDiff) * 111.0;
  }
}

enum SpoofingType { gps, rfScanner, cellTower, wifiProbe }

extension SpoofingTypeLabel on SpoofingType {
  String get label {
    switch (this) {
      case SpoofingType.gps:
        return 'GPS';
      case SpoofingType.rfScanner:
        return 'RF Scanner';
      case SpoofingType.cellTower:
        return 'Cell Tower';
      case SpoofingType.wifiProbe:
        return 'Wi-Fi Probe';
    }
  }
}
